openai_api_key: "your api key"
system_prompt_path: marble\\agent\\werewolf_prompts\\system_prompt.yaml
roles:
  - wolf
  - wolf
  - wolf
  - villager
  - villager
  - villager
  - seer
  - witch
  - guard
randomize_roles: True
use_random_names: True
villager_config:
  base_url: "https://api.together.xyz/v1"
  api_key: "your api key" 
  model_name: "meta-llama/Meta-Llama-3.1-8B-Instruct-Turbo"
werewolf_config:
  base_url: "https://api.openai.com/v1"
  api_key: "your api key" 
  model_name: "gpt-4o"
cooperation_mode: "cooperative"
use_daily_tasks: True
eval_config:
  base_url: "https://api.openai.com/v1"
  api_key: "your api key" 
  model_name: "gpt-4o"